import {
  CompassOutlined,
  UsergroupAddOutlined,
  RiseOutlined,
  HistoryOutlined,
  PlusOutlined,
  TeamOutlined,
  ReadOutlined,
  BookOutlined,
  ClockCircleOutlined,
  TagOutlined,
  GlobalOutlined,
  TrophyOutlined,
  MessageOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UserOutlined,
  HomeOutlined,
  AppstoreOutlined,
  LeftOutlined,
} from "@ant-design/icons-vue";

import {
  PhUserList,
  PhUsersThree,
  PhIdentificationBadge,
  PhUserCircleDashed,
  PhClockCounterClockwise,
  PhFolderPlus,
  PhDownloadSimple,
  PhBookOpenText,
  PhTag,
  PhUsers,
  PhPlus,
  PhClockClockwise,
  PhUsersFour,
  PhTrendUp,
  PhCardholder,
} from "@phosphor-icons/vue";
export const iconMap = {
  PhCardholder,
  PhTrendUp,
  PhUsersFour,
  PhClockClockwise,
  PhPlus,
  PhUsers,
  PhTag,
  PhBookOpenText,
  PhDownloadSimple,
  PhFolderPlus,
  PhClockCounterClockwise,
  PhUserCircleDashed,
  PhIdentificationBadge,
  PhUsersThree,
  PhUserList,
  CompassOutlined,
  UsergroupAddOutlined,
  RiseOutlined,
  HistoryOutlined,
  PlusOutlined,
  TeamOutlined,
  ReadOutlined,
  BookOutlined,
  ClockCircleOutlined,
  TagOutlined,
  GlobalOutlined,
  TrophyOutlined,
  MessageOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UserOutlined,
  HomeOutlined,
  AppstoreOutlined,
  LeftOutlined,
} as const;

// 类型导出，用于类型安全
export type IconName = keyof typeof iconMap;
